[workspace]
resolver = "2"
members = ["cli", "lib"]

[workspace.dependencies]
base64 = "0.22"
chacha20poly1305 = "0.10"
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"
secrecy = "0.10"
thiserror = "2"
zeroize = "1"
