[package]
name = "sealed"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.56", features = ["derive"] }
rand = "0.9.2"
secrecy = "0.10.3"
thiserror = "2.0.18"
zeroize = "1.8.2"
