[workspace]
resolver = "2"
members = ["cli", "lib"]

[workspace.dependencies]
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.56", features = ["derive"] }
rand = "0.9.2"
secrecy = "0.10.3"
sealed-env = { path = "lib" }
thiserror = "2.0.18"
zeroize = "1.8.2"
