[package]
name = "sealed"
version = "0.1.0"
edition = "2024"

[dependencies]
base64.workspace = true
chacha20poly1305.workspace = true
clap.workspace = true
rand.workspace = true
secrecy.workspace = true
sealed-env.workspace = true
thiserror.workspace = true
zeroize.workspace = true
